const developers = [
  {
    id: 1,
    name: "John",
    surname: "Doe",
    jobPosition: "Frontend Developer",
    image: "https://t4.ftcdn.net/jpg/03/69/19/81/360_F_369198116_K0sFy2gRTo1lmIf5jVGeQmaIEibjC3NN.jpg",
    pl: ["Html ", "CSS ", "JavaScript ", "ReactJS ", "Angular "],
    text: "John is a talented Frontend Developer with a passion for creating responsive and user-friendly web applications. He is proficient in HTML, CSS, JavaScript, ReactJS, and Angular, and he loves to stay updated with the latest frontend technologies.",
  },
  {
    id: 2,
    name: "Jane",
    surname: "Smith",
    jobPosition: "Backend Developer",
    image: "https://pspdfkit.com/assets/images/blog/2017/women-in-software-development/rita-working-d49c61e5.jpg",
    pl: ["NodeJS ", "ExpressJS ", "MongoDB ", "MySql ", ".NET "],
    text: "Jane is an experienced Backend Developer who specializes in building robust and efficient server-side applications. She is skilled in NodeJS, ExpressJS, MongoDB, MySql, and .NET technologies.",
  },
  {
    id: 3,
    name: "Alex",
    surname: "Johnson",
    jobPosition: "Full-stack Developer",
    image: "https://media.istockphoto.com/id/1135710814/photo/portrait-of-stylish-hipster-guy-with-tattoo-on-hand-writes-notes-in-computer-at-office.jpg?s=612x612&w=0&k=20&c=vpOipJpxwMJFl9UZ1H__ADLfJuVyoBESY83fDTMZ2Ao=",
    pl: ["NodeJS ", "ExpressJS ", "MongoDB ", "ReactJS ", "JAVA "],
    text: "Alex is a versatile Full-stack Developer who excels in both frontend and backend development. He's proficient in NodeJS, ExpressJS, MongoDB, ReactJS, and JAVA, making him capable of handling end-to-end development projects.",
  },
  {
    id: 4,
    name: "Sarah",
    surname: "Williams",
    jobPosition: "Mobile App Developer",
    image: "https://media.istockphoto.com/id/1081869160/photo/shes-quite-familiar-with-the-advanced-world.jpg?s=612x612&w=0&k=20&c=7eIaSWw8MCxmLVm30-YiGQQVxZbnlHV8TZZucQVmxVY=",
    pl: ["Flutter ", "SwiftUI"],
    text: "Sarah specializes in Mobile App Development, with a focus on creating innovative and user-friendly mobile applications. She is skilled in Flutter and SwiftUI and is passionate about creating mobile experiences.",
  },
  {
    id: 5,
    name: "Michael",
    surname: "Brown",
    jobPosition: "Data Scientist",
    image: "https://t3.ftcdn.net/jpg/05/40/63/14/360_F_540631446_a39tc1A3Smh7U2xbyijSEKGrx4FbJW6F.jpg",
    pl: ["Python ", "Matplotlib ", "MongoDB ", "MySql"],
    text: "Michael is a Data Scientist with expertise in data analysis and visualization. He's proficient in Python, Matplotlib, MongoDB, and MySql, and he enjoys uncovering insights from complex datasets.",
  },
  {
    id: 6,
    name: "Emily",
    surname: "Davis",
    age: 29,
    jobPosition: "UI/UX Designer",
    image: "https://media.istockphoto.com/id/1255905237/photo/female-it-developer-at-workplace.jpg?s=612x612&w=0&k=20&c=-rMSbdqmY9hZSF19peYkovxotmOmQ3KFrzTlJbmOPTk=",
    pl: ["Figma ", "Photoshop ", "Adobe Illustrator "],
    text: "Emily is a creative UI/UX Designer known for her exceptional design skills. She specializes in using tools like Figma, Photoshop, and Adobe Illustrator to create stunning and user-friendly interfaces.",
  },
];

export default developers;
